conf/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('ckeditor/', include('ckeditor.urls'))
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('feedback.urls', namespace='home_page')),
    path('users/', include('users.urls', namespace='users')),
    # path('submit-offer/', include('feedback.urls', namespace='offers-submit'))
)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback/urls.py
from django.urls import path

from feedback.views import home_page_view, comments_view, submit_offer_view, profile_view, offer_view, error_view, \
    problem_view, offers_view

app_name = 'home_page'
urlpatterns = [
    path('', home_page_view, name='home'),

    path('comments/', comments_view, name='comments'),
    path('offer/', offer_view, name='offer'),
    path('profile/', profile_view, name='profile'),
    path('submit-offer/', submit_offer_view, name='submit_offer'),
    path('problem/', problem_view, name='problem'),
    path('offers/', offers_view, name='offers'),


    path('error/', error_view, name='error'),

]

users/urls.py
from django.urls import path

from users.views import register_view, login_view, logout_view, verify_email

app_name = 'users'

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('verify-email/<str:uidb64>/<str:token>/', verify_email, name='verify-email'),
]

templates/email_not_verify.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Errors site</h1>
</body>
</html>

templates/login.html
{% load i18n %}
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login | Najot Ta'lim - Feedback site </title>
    <link rel="shortcut icon" type="ico" href="{% static 'files/images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/auth/login/style.css' %}">
    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;600;700&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap/bootstrap-icons.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap/templatemo-ebook-landing.css' %}" rel="stylesheet">

    <link rel="icon" href="{% static 'files/images/favicon.ico' %}" type="image/x-icon">
</head>

<body>

<!--  Body Wrapper -->

<div class="parent-div">
    <div class="main-div">
        <div class="main-logo">
            <a href="{% url 'home_page:home' %}" style="color: #000000">
                <img src="{% static 'files/images/logo.png' %}" alt="404" class="logo-style">
                Najot Ta'lim Feedback
            </a>
        </div>
        <div class="form-items">
            <div class="login-animation">
                <dotlottie-player src="https://lottie.host/f283573b-d8a4-42a7-a7ed-d86bc46512c9/9ZB8oMvx6e.json"
                                  background="transparent" speed="1" style="width: 400px; height: 400px;" loop
                                  autoplay></dotlottie-player>
            </div>
            <div class="login-form">
                <div class="col-lg-12 col-12 mx-auto">
                    <form class="custom-form" action="{% url 'users:login' %}" method="post" role="form">
                        {% csrf_token %}
                        <div class="text-center mb-5">
                            <p class="mb-1" style="text-align: end">{% trans 'Welcome to' %}<h6 style="text-align: end">
                            <b>{% trans 'Najot Talim Feedback' %}</b></h6></p>
                        </div>
                        <div>
                            <p style="text-align: start"><b>{% trans 'Login' %}</b></p>
                            <div class="input-group mb-3">
                                <input type="text" name="username" id="username"
                                       class="form-control login-form-input"
                                       aria-label="username" aria-describedby="basic-addon1"
                                       placeholder="{% trans 'Username' %}" required>

                                <span class="input-group-text" id="basic-addon1">
                                            <i class="custom-form-icon bi-person"></i>
                                        </span>
                            </div>
                            <div class="input-group mb-3">
                                <input type="password" name="password" id="password"
                                       class="form-control login-form-input"
                                       aria-label="user_password" aria-describedby="basic-addon1"
                                       placeholder="{% trans 'Password' %}" required>

                                <span class="input-group-text" id="basic-addon">
                                            <i class="custom-form-icon bi-person"></i>
                                        </span>
                            </div>
                            <div class="col-lg-8 col-md-10 col-8 mx-auto mb-2">
                                <button type="submit" class="form-control"
                                        style="text-align: center">{% trans 'Login' %}</button>
                            </div>
                            <div style="padding-top: 10px; text-align: center;">
                                <p style="font-size: 13px">{% trans 'Does your account not exist?' %} <a
                                        href="{% url 'users:register' %}">{% trans 'Create account' %}</a>
                                </p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--  Body Wrapper -->

<!--SCRIPT-->
<script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs"
        type="module"></script>

<!--SCRIPT-->
</body>

</html>

templates/offer-form.html
{% load i18n %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Najot Ta'lim | Offer Form</title>

    <!-- Stylesheets   -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;600;700&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap/bootstrap-icons.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap/templatemo-ebook-landing.css' %}" rel="stylesheet">

    <link rel="icon" href="{% static 'files/images/favicon.ico' %}" type="image/x-icon">

    <link rel="stylesheet" href="{% static 'css/forms/offer/style.css' %}">

    <link href="{% static 'css/bootstrap/templatemo-ebook-landing.css' %}" rel="stylesheet">

</head>
<body>
<div class="container mt-5 form-offer">
    <div class="row">
        <div class="col-md-6 animation-offer-form mb-4">
            <dotlottie-player src="https://lottie.host/5ac2c618-54f5-4971-abf3-32457e6013a0/3UMOgBkfLK.json"
                              background="transparent" speed="1" loop class="animation-offer"
                              autoplay></dotlottie-player>
        </div>
        <div class="col-md-6">
            <div class="btn-group mb-3" role="group">
                <button type="button" class="btn btn-secondary" id="signInBtn">{% trans 'Offers' %}</button>
                <button type="button" class="btn btn-secondary active" id="signUpBtn">{% trans 'Problems' %}</button>
            </div>
            <a href="{% url 'home_page:home' %}" type="button"
               class="btn btn-secondary back-home">{% trans 'Home' %}</a>
            <form method="post" action="{% url 'home_page:problem' %}" id="signUpForm">
                {% csrf_token %}
                <h4 class="form-title">{% trans 'Submit a problem' %}</h4>
                <div class="form-group mt-4">
                    <label for="problemTitle">{% trans 'Title' %}</label>
                    <input name="title" type="text" class="form-control" id="problemTitle"
                           placeholder="{% trans 'Enter problem title' %}">
                </div>
                <div class="form-group">
                    <label for="problemDescription">{% trans 'Description' %}</label>
                    <textarea name="description" class="form-control" id="problemDescription"
                              placeholder="{% trans 'Enter problem description' %}" maxlength="2000"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
            </form>
            <form method="post" action="{% url 'home_page:submit_offer' %}" id="signInForm" style="display: none;">
                {% csrf_token %}
                <h4 class="form-title">{% trans 'Submit a offer' %}</h4>
                <div class="form-group mt-4">
                    <label for="offerTitle">{% trans 'Title' %}</label>
                    <input name="title" type="text" class="form-control" id="offerTitle"
                           placeholder="{% trans 'Enter offer title' %}">
                </div>
                <div class="form-group">
                    <label for="offerDescription">{% trans 'Description' %}</label>
                    <textarea name="description" class="form-control" id="offerDescription"
                              placeholder="{% trans 'Enter offer description' %}" maxlength="2000"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
            </form>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="{% static 'js/forms/offer/script.js' %}"></script>

<!-- Animations -->
<script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs"
        type="module"></script>
</body>
</html>

templates/offer.html
{% load my_tags %}
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <title>Najot Ta'lim | Offers</title>

    <!-- CSS    -->
    <link rel="stylesheet" href="{% static 'css/offers/style.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;600;700&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap/bootstrap-icons.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap/templatemo-ebook-landing.css' %}s" rel="stylesheet">

    <link rel="icon" href="{% static 'files/images/favicon.ico' %}" type="image/x-icon">

    <link rel="stylesheet" href="{% static 'css/carusel/carusel.css' %}">

</head>
<body>
<!--navbar-->

<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="offer.html">
            <i><img src="{% static 'files/images/logo.png' %}" alt="404" style="width: 60px;"></i>
            <span>Najot Ta'lim</span>
        </a>

        <div class="d-lg-none ms-auto me-3">
            <a href="login.html" class="btn custom-btn custom-border-btn btn-naira btn-inverted">
                <i class="btn-icon bi-person"></i>
                <span>{% trans 'Log in' %}</span>
            </a>
        </div>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-lg-auto me-lg-4">
                <li class="nav-item">
                    <a class="nav-link click-scroll" href="{% url 'home_page:home' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="{% url 'home_page:offers' %}">Write an offer</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="index.html">Landing page</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="{% url 'home_page:comments' %}">Comments</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="{% url 'home_page:error' %}">404</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link click-scroll" href="profile.html">Profile</a>
                </li>

                <li class="nav-item">
                    <select class="form-select language-select" aria-label="Select language"
                            onchange="location = this.value;">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as languages %}
                        {% for language in languages %}
                            {% if language.0 != LANGUAGE_CODE %}
                                <option value="{% get_full_url request language.0 %}">
                                    {{ language.1 }}
                                </option>
                            {% else %}
                                <option value="{{ language.0 }}" disabled selected>
                                    {{ language.1 }}
                                </option>
                            {% endif %}
                        {% endfor %}
                    </select>


                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- / navbar-->

<div class="container" style="margin-top: 120px;">
    <div id="button-container">
        <div class="select-category mr-5">
            <select class="form-select" id='data-selector' aria-label="Select category">
                <option value="offers">{% trans 'Show Offers' %}</option>
                <option value="demands">{% trans 'Show Demands' %}</option>
                <option value="my-offers">{% trans 'Show My Offers' %}</option>
                <option value="my-written-offers">{% trans 'Show My Written Offers' %}</option>
            </select>
        </div>
        <div class="input-group ml-5">
            <form>
                <input type="text" class="form-control" placeholder="{% trans 'Search' %}..."
                       aria-label="Search"
                       aria-describedby="button-addon2">
                <button class="btn btn-outline-primary" type="button" id="button-addon2">
                    <i class="bi bi-search"></i>
                </button>
            </form>
        </div>
    </div>
    <div id="card-container" class="row">
        <h2 style="margin: 15px 5px">{% trans 'Offers' %}</h2>

        <!--
            Har bitta divni ichida o'zini classi bor. Ya'ni offer cardlari uchun offer degan,
            demand cardlari uchun demand degan class lari bor ular majburiy agar ushalar qolib ketsa ekranga buttonni
            bosganda malumotlarni chiqarib bermaydi. Bu classlarni nomi aynan qaysi categoriyaga
            tegishli ekanligini aniqlab beradi
        -->

        <!--   Offers      -->
        <div class="col-md-4 offer mb-4" style="margin-top: 25px">
            <div class="card">
                <div class="img-avatar">
                    <img src="{% static 'files/images/white-logo.png' %}" alt="Avatar">
                </div>
                <div class="card-text">
                    <div class="title-total">
                        <div class="title">{% trans 'Ant Collector' %}</div>
                        <a href='#'>Morgan Sweeney</a>
                        <div class="desc">Morgan has collected ants since they were six years old and now has many dozen
                            ants but none in their pants.
                        </div>
                        <div class="actions">
                            <i class="bi bi-heart">15</i>
                            <i class="bi bi-eye">25</i>
                            <i class="bi bi-chat">5</i>
                        </div>
                    </div>

                </div>


            </div>
        </div>


        <!-- Demands       -->

        <div class="col-md-4 demand mb-4" style="display: none; margin-top: 25px">
            <div class="card">
                <div class="img-avatar">
                    <img src="{% static 'files/images/white-logo.png' %}" alt="Avatar">
                </div>
                <div class="card-text">
                    <div class="title-total">
                        <div class="title">Ant Collector</div>
                        <a href='#'>Demands</a>

                        <div class="desc">Morgan has collected ants since they were six years old and now has many dozen
                            ants but none in their pants.
                        </div>
                        <div class="actions">
                            <i class="bi bi-heart">15</i>
                            <i class="bi bi-eye">25</i>
                            <i class="bi bi-chat">5</i>
                        </div>
                    </div>

                </div>


            </div>
        </div>


        <!--  My Offers      -->

        <div class="col-md-4 my-offers mb-4" style="display: none; margin-top: 25px">
            <div class="card">
                <div class="img-avatar">
                    <img src="{% static 'files/images/white-logo.png' %}" alt="Avatar">
                </div>
                <div class="card-text">
                    <div class="title-total">
                        <div class="title">Ant Collector</div>
                        <a href='#'>Morgan Sweeney</a>

                        <div class="desc">Morgan has collected ants since they were six years old and now has many dozen
                            ants but none in their pants.
                        </div>
                        <div class="actions">
                            <i class="bi bi-heart">15</i>
                            <i class="bi bi-eye">25</i>
                            <i class="bi bi-chat">5</i>
                        </div>
                    </div>

                </div>


            </div>
        </div>


        <!--    My Written Offers       -->

        <div class="col-md-4 my-written-offers mb-4" style="display: none; margin-top: 25px">
            <div class="card">
                <div class="img-avatar">
                    <img src="{% static 'files/images/white-logo.png' %}" alt="Avatar">
                </div>
                <div class="card-text">
                    <div class="title-total">
                        <div class="title">Ant Collector</div>
                        <a href='#'>My Written Offer</a>

                        <div class="desc">Morgan has collected ants since they were six years old and now has many dozen
                            ants but none in their pants.
                        </div>
                        <div class="actions">
                            <i class="bi bi-heart">15</i>
                            <i class="bi bi-eye">25</i>
                            <i class="bi bi-chat">5</i>
                        </div>
                    </div>

                </div>


            </div>
        </div>

    </div>
    <div id="pagination" class="text-center mb-4" style="margin-top: 50px;">
        <button id="prev" class="btn" disabled>Previous</button>
        <button id="next" class="btn">Next</button>
    </div>
    <div id="page-info" class="text-center"></div>
</div>

<!--footer-->

<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <span>Copyright © 2024, {% trans 'All Right Reserved' %} Najot Talim Feedback</span>
            </div>
            <!-- End Col -->
            <div class="col-md-6">
                <div class="copyright-menu">
                    <ul>
                        <li>
                            <a href="{% url 'home_page:home' %}">{% trans 'Home' %}</a>
                        </li>
                        <li>
                            <a href="#">{% trans 'Terms' %}</a>
                        </li>
                        <li>
                            <a href="#">{% trans 'Privacy Policy' %}</a>
                        </li>
                        <li>
                            <a href="#">{% trans 'Contact' %}</a>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- End col -->
        </div>
        <!-- End Row -->
    </div>
    <!-- End Copyright Container -->
</div>

<!--footer-->

<!--JAVASCRIPT FILES-->
<script src="{% static 'js/bootstrap/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap/jquery.sticky.js' %}"></script>
<script src="{% static 'js/bootstrap/click-scroll.js' %}"></script>
<script src="{% static 'js/bootstrap/custom.js' %}"></script>

<!-- Local JavaScript -->
<script src="{% static 'js/all_offers/script.js' %}"></script>
</body>
</html>

templates/problem-form.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Welcome problem site</h1>
<button><a href="/">Back to home</a></button>
</body>
</html>

templates/register.html
{% load i18n %}
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register | Najot Ta'lim - Feedback site </title>
    <link rel="shortcut icon" type="ico" href="{% static 'files/images/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/auth/register/style.css' %}">
    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@300;400;600;700&display=swap" rel="stylesheet">

    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap/bootstrap-icons.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap/templatemo-ebook-landing.css' %}" rel="stylesheet">

    <link rel="icon" href="{% static 'files/images/favicon.ico' %}" type="image/x-icon">
</head>

<body>

<!--  Body Wrapper -->

<div class="parent-div">
    <div class="main-div">
        <div class="main-logo">
            <a href="{% url 'home_page:home' %}" style="color: #000000">
                <img src="{% static 'files/images/logo.png' %}" alt="404" class="logo-style">
                Najot Ta'lim Feedback
            </a>
        </div>
        <div class="form-items">
            <div class="register-animation">

                <dotlottie-player src="https://lottie.host/a7f57d08-f75c-4eb8-b666-074b9d363f86/2M5nHp6gNm.json"
                                  background="transparent" speed="1" style="width: 400px; height: 500px;" loop
                                  autoplay></dotlottie-player>

            </div>
            <div class="register-form">
                <div class="col-lg-12 col-12 mx-auto">
                    <form class="custom-form" action="{% url 'users:register' %}" method="post" role="form">
                        {% csrf_token %}
                        <div class="text-center mb-5">
                            <p class="mb-1" style="text-align: end">Welcome to <h6 style="text-align: end"><b>Najot
                            Ta'lim Feedback</b></h6></p>
                        </div>
                        <div>
                            <p style="text-align: start"><b>{% trans 'Register' %}</b></p>
                            <div class="input-group mb-3">
                                <input type="text" name="first_name" id="full_name"
                                       class="form-control register-form-input"
                                       aria-label="full_name" aria-describedby="basic-addon1"
                                       placeholder="{% trans 'First name' %}" required>

                                <span class="input-group-text" id="basic-addon1">
                                            <i class="custom-form-icon bi-person"></i>
                                        </span>
                            </div>
                            <div class="input-group mb-3">
                                <input type="text" name="lastname" id="full_name"
                                       class="form-control register-form-input"
                                       aria-label="lastname" aria-describedby="basic-addon1"
                                       placeholder="{% trans 'Last name' %}" required>

                                <span class="input-group-text" id="basic-addon1">
                                            <i class="custom-form-icon bi-person"></i>
                                        </span>
                            </div>
                            <div class="input-group mb-3">
                                <input type="text" name="username" id="full_name"
                                       class="form-control register-form-input"
                                       aria-label="username" aria-describedby="basic-addon1"
                                       placeholder="{% trans 'Username' %}" required>

                                <span class="input-group-text" id="basic-addon1">
                                            <i class="custom-form-icon bi-person"></i>
                                        </span>
                            </div>
                            <div class="input-group mb-3">
                                <input type="email" name="email" id="email"
                                       class="form-control register-form-input"
                                       aria-label="user_email" aria-describedby="basic-addon1"
                                       placeholder="{% trans 'Email' %}" required>

                                <span class="input-group-text" id="basic-addon2">
                                            <i class="custom-form-icon bi-person"></i>
                                        </span>
                            </div>
                            <div class="input-group mb-3">
                                <input type="password" name="password1" id="password"
                                       class="form-control register-form-input"
                                       aria-label="user_password" aria-describedby="basic-addon1"
                                       placeholder="{% trans 'Password' %}" required>

                                <span class="input-group-text" id="basic-addon">
                                            <i class="custom-form-icon bi-person"></i>
                                        </span>
                            </div>
                            <div class="input-group mb-3">
                                <input type="password" name="password2" id="confirm_password"
                                       class="form-control register-form-input"
                                       aria-label="confirm_password" aria-describedby="basic-addon1"
                                       placeholder="{% trans 'Confirm Password' %}" required>

                                <span class="input-group-text" id="basic-addon3">
                                            <i class="custom-form-icon bi-person"></i>
                                        </span>
                            </div>
                            <div class="col-lg-8 col-md-10 col-8 mx-auto mb-2">
                                <button type="submit" class="form-control"
                                        style="text-align: center">{% trans 'Register' %}</button>
                            </div>
                            <div style="padding-top: 10px; text-align: center">
                                <p style="font-size: 13px">{% trans 'Do you have an account?' %} <a
                                        href="{% url 'users:login' %}">{% trans 'Log in' %}</a>
                                </p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--  Body Wrapper -->

<!--SCRIPT-->
<script src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs"
        type="module"></script>

<!--SCRIPT-->
</body>

</html>

templates/success.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h2>Succes</h2>
</body>
</html>

templates/thank_you.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Welcome offers site</h1>
<button><a href="/">Back to home</a></button>
</body>
</html>

templates/user-login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Hello world</h1>
</body>
</html>